"""add column role to users table

Revision ID: d1e22b5a5e24
Revises: f0d1f0514920
Create Date: 2026-09-11 23:12:11.378010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e22b5a5e24'
down_revision: Union[str, Sequence[str], None] = 'f0d1f0514920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users', 
        sa.Column(
            'role', 
            sa.Enum('CUSTOMER', 'KITCHEN', 'ADMIN', name='userrole', native_enum=False, length=20), 
            nullable=False,
            server_default='customer' 
        )
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
